addons:
  artifacts:
    paths:
      - ./tmp/e2e-screenshots

services:
  - xvfb
  - docker

jobs:
  include:
  - php: "7.4"
    env: WP_VERSION=latest LLMS_TRAVIS_TESTS=E2E
  - php: "8.0"
    env: WP_VERSION=latest LLMS_TRAVIS_TESTS=E2E
  - php: "8.0"
    env: WP_VERSION=nightly LLMS_TRAVIS_TESTS=E2E

