addons:
  artifacts:
    paths:
      - ./tmp/e2e-screenshots

services:
  - xvfb
  - docker

jobs:
  allow_failures:
  - php: nightly
    env: E2E=1 WP_VERSION=nightly DOCKER_COMPOSE_VERSION=1.25.0
  - php: "8.0"
    env: E2E=1 WP_VERSION=nightly DOCKER_COMPOSE_VERSION=1.25.0

  include:
  - php: "7.4"
    env: E2E=1 WP_VERSION=latest DOCKER_COMPOSE_VERSION=1.25.0
    install:
      # Upgrade docker-compose.
      - sudo rm /usr/local/bin/docker-compose
      - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
      # Setup and Install Node.
      - nvm install --lts
      # Install dependencies.
      - npm ci
      # Start the Environment.
      - composer run env up
      # Setup Environment.
      - composer run env:setup
    script:
      - npm run test
    after_script:
      - ./vendor/bin/llms-env down

  include:
  - php: "8.0"
    env: E2E=1 WP_VERSION=latest DOCKER_COMPOSE_VERSION=1.25.0
    install:
      # Upgrade docker-compose.
      - sudo rm /usr/local/bin/docker-compose
      - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
      # Setup and Install Node.
      - nvm install --lts
      # Install dependencies.
      - npm ci
      # Start the Environment.
      - composer run env up
      # Setup Environment.
      - composer run env:setup
    script:
      - npm run test
    after_script:
      - ./vendor/bin/llms-env down

  - php: "8.0"
    env: E2E=1 WP_VERSION=nightly DOCKER_COMPOSE_VERSION=1.25.0
    install:
      # Upgrade docker-compose.
      - sudo rm /usr/local/bin/docker-compose
      - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - chmod +x docker-compose
      - sudo mv docker-compose /usr/local/bin
      # Setup and Install Node.
      - nvm install --lts
      # Install dependencies.
      - npm ci
      # Start the Environment.
      - composer run env up
      # Setup Environment.
      - composer run env:setup
    script:
      - npm run test
    after_script:
      - ./vendor/bin/llms-env down

