os: linux
dist: bionic
language: php

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

import:
  - main-env.yml
  - main-php.yml
  - main-notifications.yml

jobs:
  fast_finish: true

  allow_failures:
  - env: WP_VERSION=nightly
  - env: WP_VERSION=latest RUN_CODE_COVERAGE=1
  - php: nightly

  exclude:
  # These WP Versions don't work on PHP 7.4
  - php: "7.4"
    env: WP_VERSION="5.2"
  # These WP Versions don't work on PHP 8.0
  - php: "8.0"
    env: WP_VERSION="5.5"
  - php: "8.0"
    env: WP_VERSION="5.4"
  - php: "8.0"
    env: WP_VERSION="5.3"
  - php: "8.0"
    env: WP_VERSION="5.2"

  include:
  - php: nightly
    env: WP_VERSION=latest
  - php: "7.4"
    env: WP_VERSION=latest RUN_CODE_COVERAGE=1
    before_script:
      # Download CodeClimate Test Reporter
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
    script:
      - ./cc-test-reporter before-build
      - composer run-script tests-run -- --coverage-clover clover.xml
    after_script:
      - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT

before_install:
  # Disable xDebug for faster builds
  - |
    if [ "1" != $RUN_CODE_COVERAGE ] && [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi
  # Raise PHP memory limit to 2048MB
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Install composer deps.
  - |
    if [ "8" != $( php -r "echo PHP_MAJOR_VERSION;" ) ]; then
      composer install
    else
      composer run install-php8
    fi

install:
  # Install Tests.
  - |
    if [ "8" != $( php -r "echo PHP_MAJOR_VERSION;" ) ]; then
      composer run tests-install
    else
      composer run tests-install-php8
    fi

script:
  # Check coding standards.
  - composer run-script check-cs-errors -- $( git diff --name-only --diff-filter=ACMR $TRAVIS_COMMIT_RANGE )
  # Run phpunit tests.
  - composer run-script tests-run

