###
#
# Custom workflow matrix configurations
#
# @link https://github.com/gocodebox/.github/tree/trunk/.github/actions/setup-matrix
#
###
Test PHPUnit:
  __delete:
    # Remove the LLMS Nightly job (intended for add-ons).
    - include[2]
    # Can be removed when default LLMS job matrix drops support for 5.4.
    - WP[4] # WP 5.4.
    # Can be removed when default job matrix drops support for PHP 7.3.
    - PHP[2] # PHP 7.3
