name: Coding Standards

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: Check Coding Standards

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Composer Install.
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: composer update

      # Check Coding Standards.
      - name: Run PHPCS
        run: composer run check-cs
