name: Packages Test & Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/**'

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Packages Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run pkg:lint:js

      - name: Run test suite
        run: npm run test:pkgs -- --coverage
