name: Packages Test

on:
  workflow_dispatch:
  # PRs that update package files with tests.
  pull_request:
    paths:
      - './packages/dev'
  # Once daily at 00:00 UTC.
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run test:pkgs -- --coverage

