name: Packages Lint & Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/**'

concurrency:
  group: ${{ github.workflow }}-${{ 'pull_request' == github.event_name && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run linter
        continue-on-error: true
        run: npm run pkg:lint:js

      - name: Save linter output
        continue-on-error: true
        run: npm run pkg:lint:js -- --output-file eslint-report.json --format json

      - name: Create annotations
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint-report.json"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run test suite
        # uses: artiomtr/jest-coverage-report-action@v2.0-rc.6
        uses: gocodebox/jest-coverage-report-action@master
        with:
          github-token: ${{ secrets.ORG_WORKFLOWS }}
          skip-step: install
          threshold: 50
          test-script: npm run pkg:test -- --coverageReporters="text" --coverageReporters="text-summary"
