name: Release Publication and Distribution

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  update-metadata:
    name: "Update Metadata at LifterLMS.com"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm i @lifterlms/dev

      - name: Get metadata
        run: |
          __LLMS_METADATA=$( ./node_modules/.bin/llms-dev meta parse -f json )
          echo __LLMS_PKG_VERSION=$( echo $__LLMS_METADATA | jq --raw-output '.["Version"]' ) >> $GITHUB_ENV
          echo __LLMS_WP_VERSION=$( echo $__LLMS_METADATA | jq --raw-output '.["Requires at least"]' ) >> $GITHUB_ENV
          echo __LLMS_PHP_VERSION=$( echo $__LLMS_METADATA | jq --raw-output '.["Requires PHP"]' ) >> $GITHUB_ENV
          echo __LLMS_LLMS_VERSION=$( echo $__LLMS_METADATA | jq --raw-output '.["LLMS Requires at least"]' ) >> $GITHUB_ENV

      - name: Test metadata
        run: |
          echo $__LLMS_PKG_VERSION
          echo $__LLMS_WP_VERSION
          echo $__LLMS_PHP_VERSION
          echo $__LLMS_LLMS_VERSION