name: Release Publication and Distribution

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  update-metadata:
    name: "Update Metadata at LifterLMS.com"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm i @lifterlms/dev

      - name: Run test suite
        run: ./node_modules/.bin/llms-dev meta parse -f json