name: Sync Branches
on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  sync:
    name: trunk -> dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_WORKFLOWS }}
      - name: Perform merge
        run: |
          git checkout -b dev
          git pull origin dev --ff-only --allow-unrelated-histories
          git pull origin trunk --ff-only
          git status
