name: Sync Branches
on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  sync:
    name: trunk -> dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_WORKFLOWS }}
          ref: dev
      - name: Perform merge
        run: |
          git pull origin trunk --rebase
          git status
