name: Sync Branches
on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  sync:
    name: trunk -> dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_WORKFLOWS }}
          fetch-depth: 0
      - name: Perform sync
        run: |
          git config --global user.name "branch-sync[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout dev
          git pull origin trunk --no-ff
          git status
          git push origin dev
