name: Test E2E

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        WP:
          - latest
          - nightly

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: composer run install-php8

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start Docker environment
        run: |
          composer run env up
          composer run env:setup

      - name: Update WP Version
        run: composer run env version ${{ matrix.WP }}

      - name: Set WP_VERSION env var
        run: |
          echo WP_VERSION=$( ./vendor/bin/llms-env wp core version ) >> $GITHUB_ENV

      - name: Run test suite
        run: npm run test -- --bail

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: error-artifacts
          path: tmp/artifacts
